# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-Simple-SMIME
version:      0.9
version_from: lib/Crypt/Simple/SMIME.pm
installdirs:  site
requires:
    File::Temp:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
